version: "3.3"

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:5.1.3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2181
    volumes:
      - /tmp/zookeeper/data:/var/lib/zookeeper/data
    restart: unless-stopped

  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:5.1.3
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.144.254:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /tmp/kafka/data:/var/lib/kafka/data
    restart: unless-stopped
    depends_on:
      - zookeeper
        
  elasticsearch:
    #user: $UID:$ROOTGID
    container_name: elasticsearch
    #image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    image: elasticsearch:7.17.5
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: unless-stopped
    
  kibana:
    container_name: kibana
    hostname: kibana
    image: kibana:7.17.5
    ports:
      - "5601:5601"
    environment:
       ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    restart: unless-stopped
 
    #networks:
    #  - intranet