name: Docker Image CI

on:
  push:
    branches: [ "suppress_duplicates_transactions" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image

      run: docker build --tag csbiti/pads-data-hub:latest_20 --file PadsDataHub/Dockerfile .
    - name: Lets login bitch
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Registry
      run: docker push csbiti/pads-data-hub:latest_20
